# Generated by Django 3.0.3 on 2020-03-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200228_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25.99, max_digits=10),
            preserve_default=False,
        ),
    ]
