# Generated by Django 3.0.3 on 2020-03-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_collections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collections',
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(to='shop.Collection'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
